name: NPM Publish

on:
  release:
    types: [created]

env:
  NODE_VERSION: '18.x'

jobs:
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      # No type checking, testing, or other validation steps
      
      - name: Build package
        run: npm run build:package
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
          
  notify:
    name: Notification
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: releases
          SLACK_COLOR: good
          SLACK_MESSAGE: '@cylestio/ui-dashboard has been published to npm with version ${{ github.event.release.tag_name }}'
          SLACK_TITLE: NPM Package Published
          MSG_MINIMAL: true
        continue-on-error: true 